name = "DiscStochInf"
uuid = "75d74e4b-8c64-4f53-9b14-e651a15bec74"
version = "1.0.0-DEV"
authors = ["Aditya Dendukuri (UCSB)"]

[deps]
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PROPACK = "b169e327-5944-5131-97a6-5d3d3f0a476a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LineSearches = "7.4.0"
LinearAlgebra = "1.11.0"
Optim = "1.13.2"
OrdinaryDiffEq = "6.103.0"
PROPACK = "0.5.0"
Printf = "1.11.0"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
